/**
 * Script to generate thinker library from category JSON files
 * This will populate the lookups array from all category JSON files
 */

import * as fs from 'fs';
import * as path from 'path';

interface CategoryNames {
  [categoryId: string]: string[];
}

function loadCategoryFiles(): CategoryNames {
  const categoriesDir = path.join(process.cwd(), 'data/categories');
  const files = fs.readdirSync(categoriesDir);
  const categoryNames: CategoryNames = {};

  for (const file of files) {
    if (file.endsWith('.json')) {
      const categoryId = file.replace('.json', '');
      const filePath = path.join(categoriesDir, file);
      const content = fs.readFileSync(filePath, 'utf-8');
      const names: string[] = JSON.parse(content);
      categoryNames[categoryId] = names;
    }
  }

  return categoryNames;
}

function generateLookupsCode(categoryNames: CategoryNames): string {
  const entries: string[] = [];
  
  for (const [categoryId, names] of Object.entries(categoryNames)) {
    for (const name of names) {
      entries.push(`  { name: '${name.replace(/'/g, "\\'")}', category: '${categoryId}' }`);
    }
  }

  return `import { ThinkerLookup } from '../types/thinker';

/**
 * Auto-generated lookup library from category JSON files
 * Generated by: scripts/generate-thinker-library.ts
 * Total entries: ${entries.length}
 */
export const thinkerLookups: ThinkerLookup[] = [
${entries.join(',\n')}
];
`;
}

function main() {
  console.log('Loading category files...');
  const categoryNames = loadCategoryFiles();
  
  console.log(`Loaded ${Object.keys(categoryNames).length} categories`);
  const totalNames = Object.values(categoryNames).reduce((sum, names) => sum + names.length, 0);
  console.log(`Total thinker names: ${totalNames}`);

  console.log('Generating lookups code...');
  const lookupsCode = generateLookupsCode(categoryNames);

  const outputPath = path.join(__dirname, '../lib/data/thinker-lookups.ts');
  fs.writeFileSync(outputPath, lookupsCode, 'utf-8');
  
  console.log(`✓ Generated ${outputPath}`);
  console.log(`✓ Exported ${totalNames} thinker lookups`);
}

if (require.main === module) {
  main();
}

export { loadCategoryFiles, generateLookupsCode };
